// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGAxVUiolS2Ga56D-fGyBTpUJ-9H0iQP0',
    appId: '1:415113993788:web:a656323d7550dcba2bed39',
    messagingSenderId: '415113993788',
    projectId: 'quiz-app-hello-world',
    authDomain: 'quiz-app-hello-world.firebaseapp.com',
    databaseURL: 'https://quiz-app-hello-world-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-app-hello-world.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4jNsAsct4LsVO_LPFAYfZIpN7Xzz3kUw',
    appId: '1:415113993788:android:db4610e59b61ddd42bed39',
    messagingSenderId: '415113993788',
    projectId: 'quiz-app-hello-world',
    databaseURL: 'https://quiz-app-hello-world-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-app-hello-world.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP9GUzPU_W0a1HrYyD_5leokV88kIpSOM',
    appId: '1:415113993788:ios:74ecc2cc5ad9c09b2bed39',
    messagingSenderId: '415113993788',
    projectId: 'quiz-app-hello-world',
    databaseURL: 'https://quiz-app-hello-world-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-app-hello-world.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP9GUzPU_W0a1HrYyD_5leokV88kIpSOM',
    appId: '1:415113993788:ios:74ecc2cc5ad9c09b2bed39',
    messagingSenderId: '415113993788',
    projectId: 'quiz-app-hello-world',
    databaseURL: 'https://quiz-app-hello-world-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-app-hello-world.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGAxVUiolS2Ga56D-fGyBTpUJ-9H0iQP0',
    appId: '1:415113993788:web:e592421ea0766b222bed39',
    messagingSenderId: '415113993788',
    projectId: 'quiz-app-hello-world',
    authDomain: 'quiz-app-hello-world.firebaseapp.com',
    databaseURL: 'https://quiz-app-hello-world-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-app-hello-world.firebasestorage.app',
  );

}